server:
  port: 8080
  
spring:
  h2: # http://localhost:8081/h2-console
    console:
      enabled: true
      settings:
        web-allow-others: true # for remote access    
  datasource:
    name: megatron
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:~/megatron-db;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1
    username: sa
    password: